### ISSUE TITLE
NPC Sheet unable to make proficient in saving throws

### ISSUE THREAD

**Issue by AsianDumpring** [sdenec/tidy5e-sheet#135]
After Foundry's update to 0.7.7, the Steel Defender NPC actor that one of my players created is bugged. He is unable to add his dog's proficiency bonus to either Dex or Con, only apply expertise. The modifiers are currently incorrect (as seen in the picture below). Clicking the purple box simply adds expertise. 

![image](https://user-images.githubusercontent.com/74436222/99130534-948a6f80-25de-11eb-8971-ec768e83b330.png)

**Comment by sdenec** [comment]
since the foundry update didn't change anything with the 5e system on which the sheet is based it is highly unlikely that the error is caused by the sheet. I can apply proficiency just fine to npcs. There seems to be something else going on. Maybe an active effect?
![proficiency](https://user-images.githubusercontent.com/8881200/99132785-dbe12200-2617-11eb-8f5e-461980e21496.jpg)
