### ISSUE TITLE
[Feature Request] Additional Ability Configuration

### ISSUE THREAD

**Issue by justinthejaguar** [sdenec/tidy5e-sheet#138]
Could the module enable additional abilities within the module settings with custom names on character sheets? 
For example: "Sanity" and "Honor" as referenced in the DMG.

**Comment by Fallayn** [comment]
Couldn't the resources be used for this? :)

**Comment by sdenec** [comment]
It has been quite a while since this request. I don't think I will be able to add this feature as a core mechanic to the sheet mostly because of the lack of knowledge how to do it ... Best thing would probably be another module that adds custom Abilities to characters. I don't know if this might already exist. Sorry.
