### ISSUE TITLE
Feature requests for convenience

### ISSUE THREAD

**Issue by highnrgappalachian** [sdenec/tidy5e-sheet#190]
- When unlocking a sheet, it'd be great if the trashcan icon became instantly available, for quick deletions.
- An option to show item count on NPC sheets.

**Comment by sdenec** [comment]
In order to have the item controls directly in line with the item you unfortunaley have to disable the right click menu.
Regarding item count on npc. I'll put it on my list. I do have to ask though, how many items do your npcs carry that an item count would be helpful? It mainly serves the purpose to show how many items are in a collapsed section (e. g. by inventory + on PCs)

**Comment by highnrgappalachian** [comment]
Yes, I did end up disabling the new context menu, it interferes with MARS and it's just not the workflow I'm used to since I'm transitioning from an older version of Tidy. I can see the appeal of it for other people though, it's a good addition. I would still like the trashcan to become instantly available when unlocking the sheet like in older Tidy Sheet, rather than having to first click on the dots and then choose delete. Helps just shave off a few seconds when mass deleting entries.
The lack of immediately viewable item/resource count on NPC sheets has also been a discrepancy with the default PC/NPC 5e sheet for a very long time. It's just a useful feature to have to be able to see how many bolts/arrows your NPCs have at all times, just like you do with PCs (especially since some new changes from other mods made it impossible to utilize an item that has no resources left).

**Comment by sdenec** [comment]
Ohhh, that's what you mean with item count! I didn't even realize. Yeah, I can see if NPC can actually show them and then add them ...
As for the "no dots" at least for Player Characters' items/spells/feats/effects you can choose to have the icons directly visible. From the setting choose "classic menu" (first option in the list). At any other place (favorites or npcs) because of the layout choices and sometimes additional infos I feel there is just not enough space to show them (NPC spell list especially). But I'll try and enable more places if I can.

**Comment by highnrgappalachian** [comment]
Thanks, you're awesome!

**Comment by sdenec** [comment]
I'll actually leave this issue open to help me remember^^

**Comment by sdenec** [comment]
Okay, I have added Item quantities for NPC items that have quantity enabled (as with PCs) - they fall under the categories Attack and Loot. That means weapons and everything a NPC has in its inventory will show quantity. That also means something like "claws" as it is an attack will show quantity. That can't be helped.
Also I refactored the sheet a bit, made it slightly wider and now inline item controls fit as well.
So all wishes granted in the next update I hope^^
