### ISSUE TITLE
Feature Request - Way to differentiate between Bonus and Save Throw bonus.

### ISSUE THREAD

**Issue by barraakeno** [sdenec/tidy5e-sheet#192]
![image](https://user-images.githubusercontent.com/44577670/104041054-341b4700-51b7-11eb-9568-db33d98fd373.png)

So, The way it works now: Under the ability score there are two values, the modifier on the left and the save throwing bonus on the right. My players and me keep mistaking one for another. Would be possible to rearrange the UI to make it more obvious? I'd say the modfiers are WAY more important then the saving throw bonuses, specially because the only time one needs to check it is when they are doing a saving throw, which is a roll that adds the proper value automatically. 

I would rank the info in that part of the sheet this way: MOD > Score > Save Throw Bonus.

**Comment by sdenec** [comment]
The layout is pretty much derived from the default sheet with the addition of being clickable.  The layout works fine in my opinion and let's call it an advanced feture. If you are familiar enough with it you know: skill left, safe right. Otherwise you can always click the attribute name and use the roll dialogue to unmistakenly chose what to roll for. At the moment I dont want to change how it's displayed. I could hoverever think about a different color for each field. Don't knwo thwough what would say generic roll/saving throw. grey/greenish-blue maybe?

**Comment by akrigline** [comment]
Maybe the ability be larger, with save being smaller?

**Comment by MrVauxs** [comment]
An icon next to the numbers or as a background is my suggestion

**Comment by sdenec** [comment]
In the next update I'll add my current solution for this issue. Maybe not the most elegant but it does help to make it more clear what's what and keeps the current layout.

![mod-or-save](https://user-images.githubusercontent.com/8881200/104131828-58268600-5379-11eb-9042-7006c33107ab.jpg)

**Comment by sdenec** [comment]
Middle one shows the hover state when you point your mouse on the modifiers.
