### ISSUE TITLE
[Feature Request] Grid view for NPC abilities

### ISSUE THREAD

**Issue by Wibble199** [sdenec/tidy5e-sheet#194]
Please consider adding the grid view that is present on player character sheets (inventory and spellbook tabs) to the main tab of the NPC sheet where the NPC's attacks/spells/etc are.

Thanks!

**Comment by sdenec** [comment]
I'm very happy that you seem to like the new grid layout. For NPCs though there just isn't enough space. I need the large window to the left to display the item information and that won't work with the already present skills and traits sections. That's why I didn't include it and at least for now I won't be changing the NPC sheet. I'm very sorry.
