### ISSUE TITLE
Bug: reloads spell slots and long rest

### ISSUE THREAD

**Issue by Nildran** [sdenec/tidy5e-sheet#200]
When I make a PC / NPC take a long rest, all the spell slots fall to 0 instead of recharging (even those where there are still slots left).

Moreover, when I want to manually increase the number of remaining spell slots, if I type a value and press Enter to validate, a popup appears with the image of my PC / NPC ("Foundry VTT | Rendering ImagePopout" in the console logs)

https://user-images.githubusercontent.com/59559563/104137455-19a2c280-539d-11eb-8c04-d8a267e5a54b.mp4

**Comment by sdenec** [comment]
The Long Rest setting spell slots to 0 is a 5e bug semingly introduced in 1.2.2 - can't do anything about that but will hopefully be fixed in 1.2.3!
The enter a value and on submit the charactre art opens is on my part though - still don't understand why exactly that happens but I know how to get rid of it. Will push an update!

**Comment by sdenec** [comment]
Oh, by the way - the image pops out because of a newly introduced feature: right click on the portrait lets you view either the actor portrait or token art in said pop out. I used button elements to open the popout and it seems the sheet does not like that. I'll switch out the elements, functions stays the same though. Just fyi :)
