### ISSUE TITLE
Right click menu isn't usable (and nor is disabling it)

### ISSUE THREAD

**Issue by geoidesic** [sdenec/tidy5e-sheet#228]
Something horrible has happened in the last update – suddenly the edit and favourite controls in the inventory are missing and to get to them I have to right-click. This is a night-mare because right-click also opens the standard OS right-click menu, overlayed over the module menu. So my party is no longer able to edit their inventory at all!

I tried checking the "use classic item controls in list view" option but then I get an awkward and unsuable mess (see attached).
<img width="808" alt="Screenshot 2021-01-24 at 11 24 52" src="https://user-images.githubusercontent.com/4637995/105626259-388e6380-5e37-11eb-8e8d-8c6bf34a232e.png">
 
Perhaps the item labels should be tooltips instead of trying to crowd them all into a space that's too small for label inclusion?
Also maybe you can find a way to prevent the standard right-click OS menu from appearing? (I'm on Mac OS Catalina, my players are on Windows).

Additionally the top row of controls don't seem to work at all. Clicking them does nothing. The bottom row works but causes the character sheet to flicker weirdly when clicking them. 

Overall this release is a big step backwards (sorry to say it – I love this module!). How can I revert?

**Comment by sdenec** [comment]
It looks like you have "Show midiQol buttons in context menu" enabled. That won't work with the classic menu. Disable that setting and everything should look and work fine again. Classic menu will look exactly like before. 
![midiQol-Buttons](https://user-images.githubusercontent.com/8881200/105627059-97061280-5e34-11eb-8b3d-90133223e0b8.jpg)

To conserve space there is now a right click menu enabled by default. You can a) disable right click and have a menu icon that will open the context menu on left click or - as you already figured out - use the classic menu. Currently the header flickers when the sheet redraws but that should be fixed in the next update (0.4.12). Reverting to an older version isn't possible though.
