### ISSUE TITLE
[Feature request] Changed the default options on the user side

### ISSUE THREAD

**Issue by Nildran** [sdenec/tidy5e-sheet#243]
As a GM, I use Tidy5e Sheet with the following options enabled (which are disabled by default) :

- Show trait labels
- No Inspiration Animation
- Hide if Zero
- Move Trait
- PC Toggle Trait

Most of the players I play with don't bother to configure the module options. When they are looking for information on their character sheet, it is easier for me, as a Game Master, to tell them where to look if they have the same layout as me.

Would it be possible to add an option to change the default value of the user options ?

Thanks.

PS : For the moment, I modify directly the default values in the "Settings.js" file, it is not practical and the modifications must be redone after each update.

**Comment by sdenec** [comment]
Since I want users to choose the settings they prefer there is no way to default gm preferences on all player sheets. The only way is to make the settings in advance when you create a player. While it is a bit of a hassle I think this isn't too much work since it has to be done only one time. The alternative would be to guide all your players at once through the settings and let them decide what they prefer. So no shortcuts there, sorry!
