### ISSUE TITLE
Suggestion: Passive Perception and NPC traits under resources

### ISSUE THREAD

**Issue by LadySaga** [sdenec/tidy5e-sheet#266]
Hey!
So while this is (in my opinion) the best character sheet for 5e out there, and I would never run without it, there are two little things I've been missing from it.

1: Passive Perception.
In many cases, this one is usually the same as your perception skill, but not always, and especially not for NPC creatures.
I currently don't really know where I would put that in either, so I've been manually inserting it into the Configure Senses, in the Special Senses free text box under blindsight, darkvision and so on.
I would really love if it had it's own field.
Probably also under those senses would make most sense, so we'd have:
Passive Perception
Blindsight
Darkvision
Tremorsense
Truesight
Units
Special Senses
or something like that. :)

2: Traits under Resources... for NPCs.
We can already check "PCs: Move traits below resources", and I really like that.
But we can't do that for the npc's, and many of them have very few abilities and so on, which means that the right side column of the Attributes sheet is almost empty in some cases, while the Skills and Traits need to be scrolled (if showing them all instead of hiding some).
So my suggestion is basically to allow us to toggle "**N**PCs: Move traits below resources" as well, just like we can for players. :)

Other than those 2 suggestions, I'll finish by just praising this amazing char sheet! <3

**Comment by sdenec** [comment]
Hi, in what instances doesn't your WIS + proficiency and maybe "observant" feat matches the passive perception? With items the perception could be modified with passive effects.
The Problem is that I can't change what's inside the senses configuration - that is provided by the core system. But I think the "special senses" field is quite a good place to enter custom values if the math really doesn't match the desired value.

For the "move traits" request: I got you covered. You'll find a NPC setting for that (per player option)!
