### ISSUE TITLE
tidy5e.currencyabbrcredit shows up in the currency area of the sheet when credits have been gained via a macro

### ISSUE THREAD

**Issue by franckflo** [sdenec/tidy5e-sheet#271]
I used a macro allowing to sell items for credit values. When doing so, the default sheet shows a Credit field with the number, but Tidy5esheet shows a box with the number, and this big label saying: "tidy5e.currencyabbrcredit " as you can see on the screenshot. 

![Tidy5esheet](https://user-images.githubusercontent.com/80221412/110582527-30f1f800-8121-11eb-9545-60126f6cbc35.jpg)

**Comment by sdenec** [comment]
Is it a macro or an entire mod you are using? Tidy works for currency in a way that all denominations are translated by their name. So I guess you created a new one named "credit" which gets tacked on to the translation string. Since it doesn't exist it can't be translated and thus shows the string instead.
The default sheet simply shows nothing? I can alter the function to check if there is a translation string - if not it will simply display nothing as a currency label. Alternatively I could set that the currency name which stores the values is used. So in the input field would appear "0 CREDIT".
Or if it is a module you are using ask the author kindly to provide a way to Add abbreviations that are compatible with tidy5e as the 5e custom currency module does :)

**Comment by franckflo** [comment]
Thanks for the fast answer!

It is actually a macro I picked up on Github, which allows players to sell stuff in their inventory for Credit. The default sheet shows "CREDIT" as a tag for it. 
Here is the link to the macro page on Github: https://github.com/Kekilla0/Personal-Macros/blob/master/SFRPG/GM%20Macros/Sell.js
I'm going to see if I can change the amount of money from the sale into GPs, which I think would be simpler for the players anyway. My JS-Fu is very weak however (all I know is Maptool-Script, having been a Framework-developper for that VTT in the past).

**Comment by franckflo** [comment]
I actually think I see where the problem is from: that macro was for Starfinder... I'm going to try and adapt it to DnD, which should address the issue.

**Comment by sdenec** [comment]
So in update just released I changed the translation string. Even if you don't change the macro the label should read what ever you used as the variable. Hope it helps!

**Comment by franckflo** [comment]
Thanks a bunch!
