### ISSUE TITLE
[Issue/Feature Request] NPC Rests aren't Private

### ISSUE THREAD

**Issue by Justeee** [sdenec/tidy5e-sheet#280]
The NPC rest feature is great however I don't always want my players to know how much HP one of their NPC companions has. There doesn't seem to be an option to set those chat messages to private or to even turn them off. Would love the ability to do either.

**Comment by sdenec** [comment]
Hm, I didn't wrote my own Rest function but reused the default one for Plaer Characters. There seems to be a variable check though that toggle chat output on or off. So I could include a setting that diable the chat output for NPCs. You won't get any feedback (apart from visually noticing the NPC sheet updating) when you click the rest button but your players won't get any info on the NPC rest either. So that's the option I can offer.

**Comment by Justeee** [comment]
That would be awesome!

**Comment by sdenec** [comment]
Option is now available!
