### ISSUE TITLE
Activate the weakening from the AED

### ISSUE THREAD

**Issue by Pipizio** [sdenec/tidy5e-sheet#292]
hi, I'm having a problem when I apply the weakening via DAE effect (data.attributes.exhaustion).
This is seen from the emotion at the top left of the sheet, but does not apply the type effect: half walk, half Hp, etc.
I am attaching a gif with the demonstration of the problem.
I don't even know if this is a real problem ... but more than anything else it would be useful to activate the "weakening" through the DAE

Thanks and sorry for the trouble

![test exhaust 2](https://user-images.githubusercontent.com/75280178/113066228-75216700-91ba-11eb-8b9b-427b1a8349a9.gif)

**Comment by sdenec** [comment]
You have multiple options to apply exhaustion. 
A) use the integrated effect (DM-Settings, Exhaution Effect: Tidy5e) that gets triggered when changing the exhaustion from the exhaustion menu on the portrait. It will create (currently a passive) effect with all the default modifiers for the corresponding tier.
B) create custom effects via CUB (DM-Settings, Exhaution Effect: Custom). You'll have to manually set all modifiers AND overide the exhaustion attribute in order to reflect the current tier on the character portrait. This method can be used to apply the effect from the menu or via the token's effects menu. Only caveat is, that you need a token for the actor in the current scene.
You can use this tutorial for auto replacing lower exhaustion tiers: https://www.foundryvtt-hub.com/guide/under-the-hood-enhancing-exhaustion-condition/ just modify it to override the exhaustion attribute like this (tier 3 as an example): 
![113017162-784b3180-917f-11eb-90e5-20ee0b124017](https://user-images.githubusercontent.com/8881200/113103595-c142ca80-91ff-11eb-9503-672badda827b.png)

Just applying an effect with the override won't trigger the other modifiers. Hope this helps?

**Comment by Pipizio** [comment]
Hello first of all I thank you infinitely for the quick reply.
The second point is clear to me but the first not so much.
I also noticed a small problem, when the player activates a weakening himself, this is doubled or tripled etc.
I am attaching a gif of the problem.
This happens ONLY when the player activates the weakening and the GM is CONNECTED.


![test exhaust 3](https://user-images.githubusercontent.com/75280178/113141811-77bba500-922a-11eb-88ae-518af8382ba4.gif)

**Comment by sdenec** [comment]
So, you are using the build in Effects for that? I can't confirm this bug.
Please make sure you are on the most recent tidy5e version. That should be 0.4.25

**Comment by sdenec** [comment]
Ah, no. You are not using the build in ones. They are passives, so CUB I guess? Did you set up the macro the correct way so any lower tier effects get removed?

**Comment by sdenec** [comment]
In here
```
// CUB-Exhausted macro

if (args[0] == "on") {
    var exNew = args[1].efData.label
    const levels = ["Exhaustion 1","Exhaustion 2","Exhaustion 3","Exhaustion 4","Exhaustion 5"]
    
    for(const ex of levels){
        if ((ex != exNew) && (game.cub.hasCondition(ex))){
            await game.cub.removeCondition(ex)
        }
    }
}
```
The effects in the levels array have to be named exactly as they are named in CUB, so translated into you language.
so instead of ["Exhaustion 1","Exhaustion 2","Exhaustion 3","Exhaustion 4","Exhaustion 5"] it should be ["Indebolimento 1","Indebolimento 2","Indebolimento 3","Indebolimento 4","Indebolimento 5"] presuming you have renamed the CUB Effects that way.

**Comment by sdenec** [comment]
I take it back. I can confirm this bug. Hm, I'll have to look into that.

**Comment by Pipizio** [comment]
I confirm that I am using the latest version of TIDY. (07.9 foundry- dnd5e 1.2.4)

Yes, through the weakening of the cub everything works (but that's not what I'm looking for).
The problem arises precisely when the players activate a weakening of "TIDY5e" through their card, which it duplicates.
If, on the other hand, I apply a weakening effect (as in the first gif) via DAE this is seen by the player card at the top left but does not apply the desired "TIDY" effect (half HP, half movement etc.)
It seems that the effect only applies correctly when a GM activates the weakening in the upper left with a mouse click.
If a player activates a weakening by clicking on the mouse this is duplicated (most of the time).
My intent was to create a spell that via a failed saving throw activates a weakening on the token via the DAE and that this increases by 1 each time the failed saving throw is re-rolled.

**Comment by sdenec** [comment]
I hope you found a solution for your problem and this issue didn't got lost in translation. I'll close it for now.

**Comment by Pipizio** [comment]
Sorry, the email ended up in spam and I couldn't read it.
I more or less understood the problem, in a nutshell when a player is connected and it puts a level of fatigue that is doubled when you add one after the other.
On the other hand, if you remove 1 level and add 2, it will not duplicate.
In summary, in order not to duplicate the levels of fatigue, these must be removed and put back when they accumulate.
(obviously meant for those of Tidy)
