### ISSUE TITLE
Possible issue with healing, dying, and Midi-QOL

### ISSUE THREAD

**Issue by RobTheDM** [sdenec/tidy5e-sheet#307]
During a game tonight, another player went down and was dying and making death saves. When automatically applying healing to them via Midi-QOL, the dying overlay on the sheets character portrait remained (although the red on the rest of the image went away). Only way we were able to remove it was to manually change the failed death saves to zero. I was able to replicate it in a test game of my own after the session, so it wasn't a one off. 

Considering this is a weird interaction between two different modules, I wasn't sure where to report it, but figured since the issue was visually present on the sheet, it should go here.  

![unknown](https://user-images.githubusercontent.com/66711614/114818093-01fa2200-9d70-11eb-9828-a3917f19ebf0.png)

**Comment by sdenec** [comment]
yeah, at some point down the update line I commented out a function that checks if health > 0 and saves > 0 to reset the saves. Didn't put it back in ... Only happens when you heal the token, apllying healing from the sheet will reset the saves correctly, that's why I didn't notice. But after multiple reports  I investigated. Will update! Meanwhile you can just manually set the daves to 0 to make them disappear.
