### ISSUE TITLE
[Feature request] Abilities tab as default

### ISSUE THREAD

**Issue by Newtonyd** [sdenec/tidy5e-sheet#321]
I'd like to make it so that the default tab when you open an NPC is the abilities tab. As is, it goes straight to the actions tab, which doesn't really give me a full picture of a creature. It just means one more click whenever I open a new character and want to do something with it.

Not a huge issue, but would be good QoL improvement.

**Comment by sdenec** [comment]
Since the actions tab is not part of the sheet itself but comes from the character actions module your request might be better suited there :) I bet @akrigline is able to come up with a custom setting to enable that.

**Comment by sdenec** [comment]
You can now choose if you want to open actions or attributes when you open a character sheet for the first time. New setting under the "modules" tab in tidy settings. Since sheets remember the last tab you where on it will only work if you open a sheet for an actor the first time in a session (until you refresh the game). For NPCs it should make it a little easier though.
