### ISSUE TITLE
[Feature Request] Configuration for Pop-Out Hover

### ISSUE THREAD

**Issue by erunseelie** [sdenec/tidy5e-sheet#329]
I didn't see this in the available settings, so: can a configuration be added to disable the sliding pop-out of item/feature descriptions on hover? Or is there already a manner of doing this that I accidentally missed?

**Comment by sdenec** [comment]
Depending on what inventory layout you use you can disable the slide-out card. Grid layout has mandatory slide outs (otherwise you would'nt be able to see the item info) list layout is optional. You can toggle off the list cards by unchecking "item info cards for all layouts" directly in the sheet main settings (so not in den sub menu). There are more settings below this one (show for npc/vehicle; follow cursor - which detaches the card; delay - which determins how long it takes to show the card. If you like the cards in genereal but find it annoying how quick thei appear you can put a hicher number, e. g. 1000, so you'd have to rest the cursor for 1 Second above an item to trigger the info card.

Hope this helps!

**Comment by sdenec** [comment]
Oh, this is a per user setting btw. so anyone can configure their cards how they like it best.

**Comment by erunseelie** [comment]
Awesome thanks! I did miss it haha.
