### ISSUE TITLE
Can't find creature type on NPC Sheet

### ISSUE THREAD

**Issue by Saucealicious** [sdenec/tidy5e-sheet#346]
I recently noticed that it was missing from the mobs I was using in a combat so I made a mental note to add it later on.
Now I can't seem to even find where it's supposed to be tracked. Switching to the default npc sheet shows the type right next to alignment and source so it is tracked by Foundry at least.
Am I missing something, or is the field for it simply missing in the Tidy5e sheets?
I'm still on 0.5.0 of Tidy since 0.8.X of FVTT breaks some of my crucial modules, if that has anything to do with it.

**Comment by sdenec** [comment]
0.5.0 requires 0.8.x - the sheet technically works but since the creature type are handled differently as well as attunement an some other things in in the new foundry version some things break. 0.5.4 is the latest sheet version vor 0.8.6 that fixes a few issue since the initian 0.5.x release. If you are still on foundry 0.7.x please use tidy 0.4.29! Ther was an issue where the sheet would pull the update even if it didn't support it. Either uninstall the sheet and reinstall it (you should get the last supported version) or use this link: https://github.com/sdenec/tidy5e-sheet/releases/download/0.4.29/module.json

**Comment by Saucealicious** [comment]
Ah! Yes, that fixed it. Thanks for the quick reply and thanks for the module itself, been using it since we started with FVTT.
