### ISSUE TITLE
[Question] Why so many player settings?

### ISSUE THREAD

**Issue by DarKDinDoN** [sdenec/tidy5e-sheet#358]
Hello,

Thx for this great module. This is definitely the best character sheet for 5e.

I'm wondering why most of the settings are not global?
As a GM, I took the time to configure all the little things so that the character sheet looks just like we need at the table. But I now need to ask my player to select the exact same options.

Even tho I understand that a player would want some different display on his specific character sheet, it seems to me that the benefit of having players being able to modify things is lower that the ability to have all players with the same configuration by default. The configuration intended for the table.

Not that it is related to this module, but I'm wondering if players really fiddle with module settings anyway, since they don't install modules in the first place, and probably have no idea of what most modules do.

**Comment by DarKDinDoN** [comment]
Was thinking about it and got an idea:
Some other modules use default global configuration than can be overridden at the player level.
This way the GM can define the defaults and the players can tweak the GM defaults if needed.

**Comment by sdenec** [comment]
It seemed like a good idea to give players a choice. I can see the issue for some groups when the dm wants to set up the sheet to have everyone look at the same things. My argument was that they can simply set it up once for each player.
A default global config to be overridden by players sounds good but I don't know how that would be coded. Do you maybe have an example module that has something like this? Furthermore if I change it every user would have to setup their sheet again ... But I see your point. I'll think about it but have to say it's not a priority right now :)

**Comment by DarKDinDoN** [comment]
Hmm, can't remember which module does that.
Pretty sure there was a button to display global default settings and a button for  users with the same settings but overriding global defaults.

EDIT : found it https://github.com/Norc/foundry-custom-hotbar

**Comment by Shuggaloaf** [comment]
Hi Sdenec, love this sheet. I'm with DarkDinDoN though and I strongly second this request. 

Having players go through all this setup is time consuming. Additionally, I feel that what the DM wants/requires for sheet setup far outweighs allowing Players to tweak settings. I get the desire there, but ultimately the DM should have control, not the players. 

This is especially the case with newer players who need help/direction navigating their sheet. Just for example purposes, imagine the following scenario:
• DM desired settings: Trait Labels on, Traits listed under Skills (default), Empty Character Traits shown (default). 
• Players have gone in and adjusted a bunch of settings on a per user basis.  

> DM: "Please tell me your Tool Proficiencies. They are found under your Skills on the Attributes Tab."
> 
> Player 1, *Settings left as DM desires*
> "I see them right here and my proficiencies are: blah, blah, blah"
> 
> Player 2, *Trait Labels Off*
> "Where is that? I don't see anything that says "Tool Proficiencies..."
> 
> Player 3, *Trait Labels On; Traits moved below Resources*
> "I don't have anything under my Skills list..."
> 
> Player 4, *Empty Character Traits Toggled Off*
> "I see things under Skills, but nothing that says Tool Proficiencies. You told Player 2 that there is a hammer icon, but I don't see that either..."


I get that this is perhaps an unlikely scenario, but it is just being used to highlight how there could be quite different displays for each player causing the DM to have to check each sheet and direct the players on where to find the info. What should have been a 2 minute question/answer has not taken 5+ minutes. This could apply to other settings as well so I hope that this example will help you to reconsider the importance. 

Thanks!

**Comment by sashemi** [comment]
Hi,

Tidy is a great sheet. It is the best 5e sheet I have been using for a while now. All my players prefer it strongly. You have my gratitude for developing it.

I saw the effects of this issue today. Normally I have the dark sheet setting enabled, but this is a "player" setting (ie: the setting is not stored anywhere in Foundry's data files).

So when I synced my local setup to the server, now all the sheets I see are in light mode, not dark mode.. since my remote server is different from my local.

I think all settings should at least have a global default, with overrides available for players if they need. The inconsistent player specific/global settings are really confusing.. and it's not clear which settings are which.

Thanks!

**Comment by Shuggaloaf** [comment]
>I think all settings should at least have a global default, with overrides available for players if they need.

I think this summarizes the issue nicely. Let us, as the GM, set things up the way we want globally. If an individual player wants to go in and mess with their settings after that, then that is on them. At least with global GM settings as the default, players don't have to mess with anything if they don't want to.

**Comment by Shuggaloaf** [comment]
Hi @sdenec just wondering if anymore consideration has been given to this? As you can see we have several people in the thread (or giving thumbs up) that are requesting it (I mention this as a gauge of interest not as a way to try to rush you).

The reason I'm personally following up on this is that I recently had to do a fresh install of FVTT and mods. Unfortunately this caused my group to again have to go through the process of opening settings and going through 1 by 1 and telling them what to turn on/off. 

This has also happened several other times when players are (1) using another computer/browser and (2) if they have cleared their browser's cache (or at least that is what I assume caused a settings reset for them).

To be clear _none_ of my players have any custom settings selected. It doesn't make sense to make players go through all this setup just to get to the base settings that the GM wants. Even if players _do_ want to customize an item or 2, they should only have to deal with those settings they want to change, not also go through the setup for all the other items. 

Hopefully this adds a little more insight as to a few of the reasons users are requesting this feature. Thanks!

**Comment by DarKDinDoN** [comment]
Hey,

Found a great module that can make user settings, "Global" : https://gitlab.com/kimitsu_desu/force-client-settings
It doesn't work with custom settings like Tidy 5e Sheet, but it might be worth trying to make it compatible?

Also, With only Tidy 5e left to the players to configure, it's now easier for a player to reconfigure (as the player only has this to configure).

**Comment by Shuggaloaf** [comment]
Thanks @DarKDinDoN. Appreciate the mod mention because even though I'm actually aware of that mod, others may not be. This also may be enough of a solution for some users. Unfortunately I have like a half dozen mods that use separate settings windows, but that's nice that you guys only have to deal with 1 now!

Personally I'd still rather see a solution specific to Tidy5e, rather than having it work with another mod. Helps keep mod count down and less issues when 1 mod isn't dependent on another. Or, more specifically, when 1 Dev doesn't have to rely on another to keep their code updated, fix potential conflicts, etc. That's just my take of course.

**Comment by sdenec** [comment]
Well, I can't decide if all options simply should be global - which would make thin a lot easier for me - or leave it as is. Provide a global and player override would be a real mess. And right now I don't have the time nor the motivation to do much with the sheet ... I'm happy it keeps running and doesn't need major care. That's why so many open issues or requests are still in the repo. Sorry for that!

**Comment by Shuggaloaf** [comment]
Hi @sdenec,

>Providing a global and player override would be a real mess.

Ah, I did not realize this. Definitely don't want to cause mass chaos and possibly new issues and workload for you.

>right now I don't have the time nor the motivation to do much with the sheet ... I'm happy it keeps running and doesn't need major care. 

Perfectly understandable. I can definitely get the desire to get to a good, solid point and sit back and breathe a bit. 

>I can't decide if all options simply should be global - which would make things a lot easier for me - or leave it as is. 

Since it really seems like those are the only 2 viable options without causing you undue stress, `I would vote for All Setting Global`. 
But that is just me and, again, my group doesn't customize any of their sheet options.

**Comment by DarKDinDoN** [comment]
[Force Client Settings](https://gitlab.com/kimitsu_desu/force-client-settings) can now handle settings located in custom windows.
i'm closing this.
