### ISSUE TITLE
Add "Bio/Notes" field that is editable by players with "limited" permissions

### ISSUE THREAD

**Issue by adacosta92** [sdenec/tidy5e-sheet#360]
I'm not sure how big the scope of this will end up being, but I want players to be able to take their own notes on NPCs, but now view their stats. The notes should be embedded in the actor entity just to keep all information regarding that NPC in the same place. The current Bio would be the bio according to the GM, while this new field would be for players to write their own ideas.

**Comment by sdenec** [comment]
It seems you have to be the owner of an actor to be able to open the text editor. I couldn't find an easy way to actually have an editable textbox on npcs so players with observer or limited permission can add their own text. Maybe If I dig deep into the original code I could find out why that is but I don't think it's worth the time and effort. Since this suggestion/request is a few month old I bet you found a solution anyway - otherwise I'd suggest du make a public journal entry for the players for note keeping. Sorry I couldn't help!
