### ISSUE TITLE
[FEATURE REQUEST] Exhaustion lvl & CUB

### ISSUE THREAD

**Issue by DarKDinDoN** [sdenec/tidy5e-sheet#362]
Hello,

Would it be possible to track the CUB exhaustion option the same way as the Tidy exhaustion?
Have the number highlight on the sheet, and not being able to add more than one exhaustion effect?

**Comment by sdenec** [comment]
Hi, take a look at this tutorial: https://www.foundryvtt-hub.com/guide/under-the-hood-enhancing-exhaustion-condition/
If I understand your question correctly you will have to do some macros to achive what you want. Also set the exhaustion tracker for tidy to the custom option in the settings. This combination should get you where you want. One thing though: With the CUB option there has to be a token present in the scene in order to apply the effect - otherwise you'll get an error notice when you try to set exhaustion from the character sheet :) I hope this helps!

**Comment by DarKDinDoN** [comment]
Thx for the link. Will definitively test that!

What about tracking on sheet as well?
![image](https://user-images.githubusercontent.com/1687854/122993126-39f09780-d3a7-11eb-817d-9213a6a99a2f.png)

**Comment by sdenec** [comment]
Ah, yes. Extend the CUB condition to actually set the actors exhaustion value (I think override is the correct setting) to the corresponding tier!

**Comment by sdenec** [comment]
For exhaustion 1 it would be
data.attributes.exhaustion -> Override -> 1

change the number accordingly in the other exhaustion tiers!

**Comment by DarKDinDoN** [comment]
Yes, it's working! Thx!
