### ISSUE TITLE
Enhancement: support integration with midi qol inspiration

### ISSUE THREAD

**Issue by SR5060** [sdenec/tidy5e-sheet#367]
Midi qol recently added support for inspiration effects. Would be great if the tidy sheet inspiration could integrate with this feature (or provide some level of native support) as your approach is visually much cleaner

**Comment by sdenec** [comment]
Can you elaborate? The inspiration on the tidy sheet is just a reskin of the default inspiration. It's essentially still the simple checkbox just with a in depth styling approach. So if the midi qol features works in the default sheet it "should" (tm) work on my sheet ...

**Comment by SR5060** [comment]
Oh gotcha, so this may be out of scope for your module but I'll elaborate and let you determine that. Essentially midi qol enhancements active effects to automate the inspiration ability, so I think the support here would be to have the inspiration checkbox be able to create an "effect" on the pc

**Comment by kaelad02** [comment]
Best I can tell they're referring to the GM Inspiration item that's included in the Midi QOL Sample Items compendium in this update.

https://gitlab.com/tposney/midi-qol/-/blob/master/Changelog.md#anchor-0821

I think triggering the same effect that item has just by having inspiration is a bad idea. The checkbox on the character sheet is a reminder to the player that they have inspiration. That's not what the active effect is. It's the mechanical implementation, granting advantage on the next roll and automatically removing itself with those special durations dae/midi has.

Unless OP was thinking there could be another button on the sheet to "use their inspiration," unchecking the inspiration checkbox and setting the effect. Thinking about it more, that's probably what they were asking for. But in that case I'd just suggest using the item itself or Convenient Effects since it comes with the same effect.

**Comment by SR5060** [comment]
Yea you are right I was thinking "using inspired" (deselecting) would add the active effect. But this was before the convenient effect module existed which I agree is probably the right way to go now

**Comment by sdenec** [comment]
Thanks for looking into this and clarifying. I'll close this issue then :)
