### ISSUE TITLE
[Feature] Containers that can contain things

### ISSUE THREAD

**Issue by tagnullde** [sdenec/tidy5e-sheet#380]
For the longest time I wanted to have my adventuring gear "in" my backpack. So I can keep track of
the things on my character and in the backpack. But in the past only a bunch of outdated modules tried to fix the issue.

Now I found the [character sheet obsidian](https://bitbucket.org/Fyorl/obsidian/wiki/User%20Guide). And the developer
managed to make functional containers in the inventory. (search for container on the linked site)

Could you implement something similar?

**Comment by sdenec** [comment]
I'm not smart enough to develop something like this on my own. But I would suggest using inventory+ to add custom inventory categories like "backpack" or "bag of holding" and sort stuff into them. Works well enough for me. Little disclaimer: i+ currently has a bug where weight is listed as NaN/300 for example. It has been fixed by the community but not jet implemented into an update.

**Comment by tagnullde** [comment]
inventory+ never really satisfied my needs. Still: Fair enough. :)
