### ISSUE TITLE
Attributes Page Display Error on Firefox

### ISSUE THREAD

**Issue by DivertedCircle** [sdenec/tidy5e-sheet#39]
The Attributes page is squished together and misaligned when viewed in Firefox. Running Foundry 0.6.2, D&D 5e 0.93, and Tidy Sheet 0.2.2. May be similar to an issue Alt5e had when ran in Firefox: https://discord.com/channels/170995199584108546/648215359895240715/722184760654561350

![image](https://user-images.githubusercontent.com/26470570/85335181-c9fcb800-b499-11ea-8933-29e97940cc04.png)

**Comment by sdenec** [comment]
2 issues are meeting up there. a) firefox renders the single skills 1px too high, thus pushing them out of their bounds - this will be fixed in the next update. b) the skill modifier module forces the skill list to expand in width, pushing it below the abilites. this should be fixed with the next update by the modules author!

**Comment by DivertedCircle** [comment]
Version 0.2.3 appears to have partially fixed the bug, however there are still visual issues. The image below is running version 0.2.3 on Firefox with all other modules disabled.
![image](https://user-images.githubusercontent.com/26470570/85419502-6755fb80-b52f-11ea-8b7b-cd25a270ae18.png)
