### ISSUE TITLE
Minor Feature Request - Add support for the token wildcards feature

### ISSUE THREAD

**Issue by p4535992** [sdenec/tidy5e-sheet#412]
On the character sheet image if the token image is set as a wildcard, the "show token" feature returns an empty image.

It is not an essential feature, but in the meantime I point it out.

**Comment by sdenec** [comment]
This is because the actor doesn't have an actual token image assigned but the wildcard character - thus, resulting in a "file not found" error. I don't think I can show the wildcard token because I can't possibly know which token should be used since all tokens point to the same actor and it doesn't seem there is a value on that actor that stores the ranomized image ... So no feature support there, sorry!

**Comment by p4535992** [comment]
No problem
