### ISSUE TITLE
Item details sheet does not display in v9

### ISSUE THREAD

**Issue by SR5060** [sdenec/tidy5e-sheet#467]
Tidy sheet works normally in the character sheets but the payout reverts to the standard layout when an item/feature sheet is opened. Foundry, dnd5e and tidy module are all up to date

**Comment by Ghostdesu** [comment]
I had the same issue, turns out the problem is just that the default sheet was reset. 
Going into sheet -> default:tidy5e in item menu worked for me. (had to do it separately for items, features and spells)
![image](https://user-images.githubusercontent.com/31375910/149174412-8b049705-97fa-4ad5-b59b-9a4969f43067.png)

**Comment by SR5060** [comment]
Oh wow, you're right. Thanks!
