### ISSUE TITLE
Sugestion : Integration with Item Collection Module

### ISSUE THREAD

**Issue by Thedvdias** [sdenec/tidy5e-sheet#470]
It's straight as the the title goes. Since backpacks suck in the core game most people end up using Tim Posney's Item Collection Module. It's an amazing module but god damn the sheets look bad. I think would be a great addition :)

**Comment by p4535992** [comment]
The request goes outside the scope of this module , also because now there are several modules doing that job "Inventory PLus", "Backpack manager", "Simple Loot List" and it would be impossible to predict all use cases and needs of all of them.
The request then should not be made here but on the item container project for add asetting for use the tidy sheet instead of the dnd5e standard.
This issue can be closed.
