### ISSUE TITLE
Short rest for NPC does long rest instead

### ISSUE THREAD

**Issue by chadviolin** [sdenec/tidy5e-sheet#481]
Long rests for NPCs work fine, but when clicking short rest, the NPC takes a long rest instead.

**Comment by sdenec** [comment]
I think that is because originally NPCs don't use rests and the only rest option available to them is the long rest - so either button gives you the long rest function despite the short rest button calling the short rest function. I didn't change anything on the NPCs, just revealed to rest option. Sorry!
![npc_rest](https://user-images.githubusercontent.com/8881200/157909641-4ac5ed70-8fea-4eb2-935d-10493f6d2915.jpg)
