### ISSUE TITLE
Base context menu and tidy5e context menu open at the same time.

### ISSUE THREAD

**Issue by szefo09** [sdenec/tidy5e-sheet#626]
![image](https://user-images.githubusercontent.com/37833135/212091083-f1ac8dbd-8d87-49c6-8cc4-a38f0b408099.png)

This behavior can be temporarily circumvented by going to the "Sheet Settings", "GM Options" tab and enabling "Disable right click context menu."

**Comment by Kharmans** [comment]
This is happen to me too.

**Comment by Leondthurrell** [comment]
Any errors in the console when this is happening?

**Comment by Kharmans** [comment]
> Any errors in the console when this is happening?

No, but this shows when I open the sheet.
![image](https://user-images.githubusercontent.com/112586547/212335325-2a896c9a-96cc-4ebe-bed2-2ea23a9ab513.png)

**Comment by sdenec** [comment]
ATTENTION! Tidy5e is now updated for the latest DND 5e release (2.1.x). When you have journal data in your sheet you WILL lose it when you transition from 2.0.3 to 2.1.x - In order to save it you have to execute the Macro in the readme https://github.com/sdenec/tidy5e-sheet#readme BEFORE you make the upgrade. If you do have a backup from before the switch you can recover your data this way. Sorry for any inconveniences.
