### ISSUE TITLE
Notes that are specific to Tidy5e Sheet are removed in DnD5e 2.1 system

### ISSUE THREAD

**Issue by szefo09** [sdenec/tidy5e-sheet#627]
Custom values can no longer be stored in `system.details`, and are wiped on first load of the world and on save, it's recommended to migrate to `actor.flags.tidy5e-sheet.details` to preserve the data.

**Comment by aquavitae** [comment]
Any suggests about how to do the migration?

**Comment by MrPrimate** [comment]
Once the system is migrated that data is gone. Ideally, we want to add a world setting that checks to see if a migration is needed (e.g. store the Tidy 5e version that last migrated data in there). In a early hook we would check to see if migrations need to take place, if they do, we migrate.

The migration would loop over each world actor and check the various extra fields that tidy5e is using, and pop them into the appropriate flag on the actor. The rest of the module would be adjusted to read/save to these flags instead of the `system.details` fields.

**Comment by MrPrimate** [comment]
It looks like @p4535992 has given it a good go here: https://github.com/sdenec/tidy5e-sheet/pull/622/files

**Comment by szefo09** [comment]
This one-liner could fast-migrate all the data. It's a dirty method though, as it will add this flag to every character.
```js
//Update old tidy5e data
game.actors.updateAll((actor)=>{
    return {
        "flags.tidy5e-sheet.details":{
            gender:actor.system.details.gender,
            age:actor.system.details.age,
            height:actor.system.details.height,
            weight:actor.system.details.weight,
            eyes:actor.system.details.eyes,
            skin:actor.system.details.skin,
            hair:actor.system.details.hair,
            notes1name:actor.system.details.notes1name,
            notes1:actor.system.details.notes1,
            notes2name:actor.system.details.notes2name,
            notes2:actor.system.details.notes2,
            notes3name:actor.system.details.notes3name,
            notes3:actor.system.details.notes3,
            notes4name:actor.system.details.notes4name,
            notes4:actor.system.details.notes4
        }
    }
})
```

**Comment by sdenec** [comment]
ATTENTION! Tidy5e is now updated for the latest DND 5e release (2.1.x). When you have journal data in your sheet you WILL lose it when you transition from 2.0.3 to 2.1.x - In order to save it you have to execute the Macro in the readme https://github.com/sdenec/tidy5e-sheet#readme BEFORE you make the upgrade. If you do have a backup from before the switch you can recover your data this way. Sorry for any inconveniences.
