### ISSUE TITLE
Trait configuration window fails to open in DnD5e 2.1 system

### ISSUE THREAD

**Issue by szefo09** [sdenec/tidy5e-sheet#628]
With changes to how traits work in DnD5e system 2.1, the trait configuration (Senses, Languages, Damage Immunities, Tool Proficiencies, etc.) window fails to open. Possible fix:
https://github.com/sdenec/tidy5e-sheet/blob/6a214f4f48e72fc1029b5cd86ff715fd92e29018/src/templates/actors/parts/tidy5e-traits.html#L29
To enable opening of the Languages Configuration, change to:
```html
<a class="trait-selector" data-options="languages" data-trait="languages"><i class="fas fa-pencil-alt"></i></a>
```
Similar with other Tabs, except for Proficiencies Tab, which requires a change like this:
https://github.com/sdenec/tidy5e-sheet/blob/6a214f4f48e72fc1029b5cd86ff715fd92e29018/src/templates/actors/parts/tidy5e-traits.html#L128
Change to:
```html
    <a class="trait-selector" data-trait="armor"><i class="fas fa-pencil-alt"></i></a>
```

**Comment by sdenec** [comment]
ATTENTION! Tidy5e is now updated for the latest DND 5e release (2.1.x). When you have journal data in your sheet you WILL lose it when you transition from 2.0.3 to 2.1.x - In order to save it you have to execute the Macro in the readme https://github.com/sdenec/tidy5e-sheet#readme BEFORE you make the upgrade. If you do have a backup from before the switch you can recover your data this way. Sorry for any inconveniences.
