### ISSUE TITLE
Toggleable 'Hide Spellbook' option for Player sheets for characters with no spells.

### ISSUE THREAD

**Issue by dacaz5** [sdenec/tidy5e-sheet#63]
Would be useful to be able to hide the spellbook tab for characters with no spells.

**Comment by sdenec** [comment]
This is kind of impracticable. Each character would need to have a button to toggle the visiblity of the tab. So instead of the tab you would have an additional button to toggle it. If it is a global setting it will affect all characters. Also If you have magic items that add spells to your repertoire you couldn't access them because you have no spell book. I don't think having the tab - even if empty is that much of a nuissance to go through the troubles to hide it. Sorry!
