### ISSUE TITLE
Errors in log when trying to add favorite

### ISSUE THREAD

**Issue by MorganVergara** [sdenec/tidy5e-sheet#632]
Greetings,

When using the Tidy 5e sheet, and trying to add an item as a favorite, I get some strange behavior. First, the base menu shows up along with the Tidy menu when I right click on an inventory item.

![image](https://user-images.githubusercontent.com/30846057/213329890-fed082cb-bab8-4c89-9dbe-0db562f5b95a.png)

Second, I see this error in the console:

![image](https://user-images.githubusercontent.com/30846057/213330002-b1d80fa4-0312-409f-beda-ae831c39c361.png)

Find the culprit seems to indicate the problem is in Tidy5e sheet. (I had libWrapper and socketLib also loaded, but I don't think it's one of those.)

Any ideas?

Thanks!

Morgan

**Comment by sdenec** [comment]
There is a huge overhaul regarding various issues on its way. I bet this is one of the fixed issues :) No eta, though. But soon.

**Comment by sdenec** [comment]
ATTENTION! Tidy5e is now updated for the latest DND 5e release (2.1.x). When you have journal data in your sheet you WILL lose it when you transition from 2.0.3 to 2.1.x - In order to save it you have to execute the Macro in the readme https://github.com/sdenec/tidy5e-sheet#readme BEFORE you make the upgrade. If you do have a backup from before the switch you can recover your data this way. Sorry for any inconveniences.

**Comment by MorganVergara** [comment]
Awesome, thanks! I'll try it and let you know how it works.

Morgan
