### ISSUE TITLE
HP being modified when the sheet is closed.

### ISSUE THREAD

**Issue by Brimcon** [sdenec/tidy5e-sheet#633]
With the new system update and testing via #622 when you close the sheet fully it overrides the HP configuration with whatever is in the HP bar.

Attempting to fix the HP configuration by deleting the override causes HP to go to 0.

Expected result: HP remains "unchanged" And will act accordingly to Class HP, Per Level Bonus and Overall Bonus.

**Comment by sdenec** [comment]
ATTENTION! Tidy5e is now updated for the latest DND 5e release (2.1.x). When you have journal data in your sheet you WILL lose it when you transition from 2.0.3 to 2.1.x - In order to save it you have to execute the Macro in the readme https://github.com/sdenec/tidy5e-sheet#readme BEFORE you make the upgrade. If you do have a backup from before the switch you can recover your data this way. Sorry for any inconveniences.
