### ISSUE TITLE
Favourites not working for spells or inventory pages. 

### ISSUE THREAD

**Issue by nirurin** [sdenec/tidy5e-sheet#636]
Favourites for features still works, as it has its own button, but the other pages don't come up with the option anymore.

**Comment by sdenec** [comment]
ATTENTION! Tidy5e is now updated for the latest DND 5e release (2.1.x). When you have journal data in your sheet you WILL lose it when you transition from 2.0.3 to 2.1.x - In order to save it you have to execute the Macro in the readme https://github.com/sdenec/tidy5e-sheet#readme BEFORE you make the upgrade. If you do have a backup from before the switch you can recover your data this way. Sorry for any inconveniences.
