### ISSUE TITLE
level up feature dont work in other language

### ISSUE THREAD

**Issue by CaosFR** [sdenec/tidy5e-sheet#640]
Hi,

I cannot level up with the button in the character sheet beceauce class names are translate in french. There is a way to disable / hidden this option or tweak it ? 

Thanjs

![image](https://user-images.githubusercontent.com/37581932/214973391-e7a2a2e7-d1be-4bf3-aecf-5466d37fd365.png)

**Comment by sdenec** [comment]
ATTENTION! Tidy5e is now updated for the latest DND 5e release (2.1.x). When you have journal data in your sheet you WILL lose it when you transition from 2.0.3 to 2.1.x - In order to save it you have to execute the Macro in the readme https://github.com/sdenec/tidy5e-sheet#readme BEFORE you make the upgrade. If you do have a backup from before the switch you can recover your data this way. Sorry for any inconveniences.
