### ISSUE TITLE
BETA BUG: Max Prepared Spells doesn't save.

### ISSUE THREAD

**Issue by GambetTV** [sdenec/tidy5e-sheet#642]
For whatever reason, when you close a character sheet, the Maximum Prepared Spells resets to 0. 

![image](https://user-images.githubusercontent.com/72000497/215117774-c3ce0716-23bc-4a7f-9d63-e176ac6acbbd.png)

**Comment by p4535992** [comment]
Fixed

**Comment by sdenec** [comment]
ATTENTION! Tidy5e is now updated for the latest DND 5e release (2.1.x). When you have journal data in your sheet you WILL lose it when you transition from 2.0.3 to 2.1.x - In order to save it you have to execute the Macro in the readme https://github.com/sdenec/tidy5e-sheet#readme BEFORE you make the upgrade. If you do have a backup from before the switch you can recover your data this way. Sorry for any inconveniences.
