### ISSUE TITLE
BETA BUGS: Double Flags on Favorites, Favorites in random order, Disable Duplicate button please

### ISSUE THREAD

**Issue by GambetTV** [sdenec/tidy5e-sheet#643]
This is looking real good! Just a couple observations from a user point of view:

1. It looks like Favorited items are in random order rather than alphabetical.

2. I am unclear on why a second flag shows up on favorited items. When you favorite an item you have to click on a little flag symbol which is grayed out, but then highlights when active, and now a second flag symbol pops up to the left of the item's weight. Just feels like unnecessary clutter.

3. There needs to be a way to disable the Duplicate button. People are gonna accidentally hit this, and it doesn't even prompt you to make sure you meant to duplicate an item. Also I don't even know what the use case is for duplicating Spells or Class/Race features. At this very least this button should go invisible when the character sheet is locked, but I'd vastly prefer an option in Tidy5e Settings where I can simply disable this completely for Players and the GM so it doesn't even show up.

That's really it! This is a great effort, and I thank you all for keeping this module alive!

**Comment by p4535992** [comment]
1) It looks like Favorited items are in random order rather than alphabetical. 
_fixed_
2) I am unclear on why a second flag shows up on favorited items. When you favorite an item you have to click on a little flag symbol which is grayed out, but then highlights when active, and now a second flag symbol pops up to the left of the item's weight. Just feels like unnecessary clutter. 
_i personally think it makes it clearer, but for now it remains in case someone disables "classic controls" with the setting module or they would lose track of their favorites _
3) There needs to be a way to disable the Duplicate button. People are gonna accidentally hit this, and it doesn't even prompt you to make sure you meant to duplicate an item. Also I don't even know what the use case is for duplicating Spells or Class/Race features. At this very least this button should go invisible when the character sheet is locked, but I'd vastly prefer an option in Tidy5e Settings where I can simply disable this completely for Players and the GM so it doesn't even show up.

_I am not sure on what is the best solution whether to disable it for all non-GMs or something else, for now I put it in the same control as the delete us command so that it is disabled with the padlock_

**Comment by sdenec** [comment]
ATTENTION! Tidy5e is now updated for the latest DND 5e release (2.1.x). When you have journal data in your sheet you WILL lose it when you transition from 2.0.3 to 2.1.x - In order to save it you have to execute the Macro in the readme https://github.com/sdenec/tidy5e-sheet#readme BEFORE you make the upgrade. If you do have a backup from before the switch you can recover your data this way. Sorry for any inconveniences.
