### ISSUE TITLE
Deleting spell locks NPC sheet in 0.8.8

### ISSUE THREAD

**Issue by Lwftmb** [sdenec/tidy5e-sheet#644]
This is our go-to character sheet and I appreciate all the effort to maintain the module.

I've been trying the 0.8.8 test code and the only problem I have seen is that after you delete a spell from an NPC sheet, the spell remains visible on the sheet until closed.
Once that sheet has been closed the sheet will not re-open.
This only happens on the NPC sheet, the PC sheet doesn't have the issue.

Here's the accompanying error text from the log that occurs when you try to re-open the NPC sheet.

![TidySheet capture 2023 01 27](https://user-images.githubusercontent.com/123787328/215237244-4ff3cb45-4b66-4b04-8dea-7f2ccffe0f6e.PNG)

**Comment by p4535992** [comment]
Sorry i can't replicate the issue, try out 0.8.10, maybe i fixed this without knowing, if the issue persist pass to me the npc with the problem on discord

**Comment by sdenec** [comment]
ATTENTION! Tidy5e is now updated for the latest DND 5e release (2.1.x). When you have journal data in your sheet you WILL lose it when you transition from 2.0.3 to 2.1.x - In order to save it you have to execute the Macro in the readme https://github.com/sdenec/tidy5e-sheet#readme BEFORE you make the upgrade. If you do have a backup from before the switch you can recover your data this way. Sorry for any inconveniences.
