### ISSUE TITLE
Automatic Hit Point calculation reverts to 0

### ISSUE THREAD

**Issue by ctbritt** [sdenec/tidy5e-sheet#647]
under the new 2.1.x automatic max hp calculation, if you delete the manual HP it reverts to for the auto-calc HP max. 

I swear, this 2.1.x update was as bad at breaking things as the v9 to v10 was.

**Comment by p4535992** [comment]
Sorry maybe I didn't quite understand the use case, but it looks like another one that was pointed out to me. To give the choice on this behavior i have created the module setting `"Allow Hp Max override on Character"` to do the override of the max hp calculation. If you want only the GM to be able to edit that field there is a second module setting `"Lock change hp max for non GM"` for enable that.

**Comment by p4535992** [comment]
I mean on the the beta, you can find the link here : https://github.com/sdenec/tidy5e-sheet/pull/622

**Comment by sdenec** [comment]
ATTENTION! Tidy5e is now updated for the latest DND 5e release (2.1.x). When you have journal data in your sheet you WILL lose it when you transition from 2.0.3 to 2.1.x - In order to save it you have to execute the Macro in the readme https://github.com/sdenec/tidy5e-sheet#readme BEFORE you make the upgrade. If you do have a backup from before the switch you can recover your data this way. Sorry for any inconveniences.
