### ISSUE TITLE
BUG: Inventory Favorite list does not separate between Weapons/Equipment/Consumables/etc.

### ISSUE THREAD

**Issue by GambetTV** [sdenec/tidy5e-sheet#661]
I could have sworn this was a thing prior to the most recent updates. But now my Favorited Inventory list is just smashed together alphabetically with no organization. Would be great if this could separate out again.

**Comment by p4535992** [comment]
I verified that in the old one it was like that, no separation between Weapons/Equipment/Consumables so it is not a bug if anything it is a new feature.
The sorting is alphabetical because you had requested it here https://github.com/sdenec/tidy5e-sheet/issues/643 and it was the "old" behaviour too or there is something else i miss ?

**Comment by GambetTV** [comment]
Nah, if it's not supposed to be sorted then that's fine, if not ideal.
