### ISSUE TITLE
Number of prepared spells are not imported anymore

### ISSUE THREAD

**Issue by TyrasNistru** [sdenec/tidy5e-sheet#680]
Since the update, when the number of max prepared spells number is not imported when importing class levels. It's always zero. Used to work right before the update.

As other issues indicate, this is likely due to the changing of the field to the new `flags.tidy5e-sheet.maxPreparedSpells,` that broke compatibility with (all) the mods that use the old field `system.details.maxPreparedSpells`. 

**To reproduce:**
Use the 5e Importer to import levels of a caster class (such as wizard or artificer)
Go to the Spellbook tab.
The max prepared spells is zero.

**Expected Behavior:**
The "Max Prepared Spells" field to contain how much spells you can prepare.

**Browser:**
Any. But confirmed with:
Foundry embedded browser
Mozilla Firefox 109.0.1
Google Chrome

**Foundry Version:**
V10 - Build 291

**Game System:**
DnD 5e 2.1.4

**Observation:**

Even if you edit the "Prepared Spells" effect to use the new flag, It only shows the correct value for a little while, and then goes back to show zero until you edit the effect and save again. 

I don't know all the actions that cause the "reset to zero", but looks like any modification in any spell at all triggers it. so far I confirmed that the following actions causes a reset:

Preparing/Unpreparing a spell;
Casting a spell;
Adding or removing a spell to/from the list;
Reordering a spell;
Editing a spell;

After the "reset to zero" triggers, the only way to make it work again (until another reset is triggered) is to:

Edit the effect to remove the formula and put a literal value in the "Effect value" field (like 4)
Save the Effect
Edit the effect again and put the formula back.

![image](https://user-images.githubusercontent.com/9531350/216995801-e42d1e19-1e68-46be-a856-bb93d89f76d8.png)

**Comment by TyrasNistru** [comment]
Also, changing the field to be updated by the "Spells Prepared" effect manually doesn't work. Just make the field uneditable with the tooltip "This value is being modified by an Active Effect and cannot be edited. Disable the effect to edit it"

**Comment by p4535992** [comment]
Sorry but I didn't understand what do you mean by "Max Imported Spells" ? the "Max Prepared Spells" ?
And please if you want to help make more detailed tickets 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Browser:**
 - 

**Foundry Version:** 

**Game System:** 

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by TyrasNistru** [comment]
I edited the issue to be more clear about the issue.

**Comment by p4535992** [comment]
Try out 0.8.18

**Comment by TyrasNistru** [comment]
Seems to be working on 0.8.20, with the addendum of it must be set to "custom" instead of "override", but I suppose that's intended
