### ISSUE TITLE
Request on NPC sheets

### ISSUE THREAD

**Issue by MagatsuNimura** [sdenec/tidy5e-sheet#73]
Hi! 
As a DM I find super useful to have attack, features, actions and even inventory and spellbook all expanded as a default. Having to expand all of this one by one to check what a monster does on the fly is a bit cumbersome. 

I'd love if the module had an option for npc or pc sheets to have all of this expanded as a default, so you can turn this on or off depending on your preferences.

Thank you for the module in any case!

**Comment by sdenec** [comment]
Hi, can you specify what you mean? Neither the PC Sheet nor the NPC Sheet has a feature to collapse/expand sections ...

**Comment by MagatsuNimura** [comment]
Sorry, maybe I've explained myself wrong here (not my first language) I'll try to explain myself better.

In the NPC sheet aswell as the PC sheet (although for me it is more important in the NPC sheet), your features or actions for the npc come collapsed and you can only read the title of the feature/action. You have to clic on the name to expand and read the detailed explanation like reach, range, kind of damage and that kind of stuff. Same happens for example if an npc has multiattack. You can read the title of the feature at first glance (multiattack) but the number of attacks, or types of attacks are written in text in the collapsed box.
I'll attach a screenshot for reference, where the melee action is collapsed, and the ranged action is expanded.

![tidy sheet](https://user-images.githubusercontent.com/69247369/89503786-5acbf080-d7c7-11ea-84ec-ec861bbf0efb.jpg)

I'd love to have all that information at first glance, all expanded, as an option :)

Thank you for the response.

**Comment by sdenec** [comment]
Oh, I see. Well, that is the default way it works in every Sheet as provided by the dnd5e core functions (as far was I have seen it). You have to actually click the names to even add the information to the sheet and make it visible (so all the information gets added dynamically to the sheet). So sadly I can't make everything visible as easy because I didn't wrote this part of the code. And since this request is not a common thing I won't put in the hours to try and figure something out - at least for now - Sorry!

**Comment by MagatsuNimura** [comment]
Thank you anyways for taking the time to answer :)
